---
name: Load Oxigraph DB and Query
on:
    push:
        branches:
            - main
        paths:
          - 'src/oxigraph_server.jl'
    workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: ~1.7.0-0

            - name: Run Oxigraph DB Load & Query
              run: make oxigraph-db-load
