---
name: Update Viz
on:
    push:
        branches:
            - main
        paths:
          - 'src/**'
    workflow_dispatch:
    schedule:
      - cron: "0 3 * * *"
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: "~1.7.0-0"

            - name: Run ESEF Visualization
              run: make build-viz
              env:
                TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

            - uses: EndBug/add-and-commit@v7
              with:
                add: figs
                author_name: Update Bot
                author_email: updatebot@updatebot.updatebot
                message: 'Autoupdate Visualizations'
